# Generated by Django 4.2.5 on 2023-09-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="author",),
    ]
