# Generated by Django 4.2.5 on 2023-09-22 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("book", "0002_remove_book_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="chapter",
            name="EditUser",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="EditUserChapter",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
